<?php

use Drupal\core\Url;
use Drupal\Core\Link;
use Drupal\node\Entity\Node;
use Drupal\views\Views;
use Drupal\paragraphs\Entity\Paragraph;
use Drupal\file\Entity\File;
use Drupal\image\Entity\ImageStyle;
use Drupal\Core\Menu\MenuLinkInterface;
use Drupal\menu_link_content\Plugin\Menu\MenuLinkContent;
use Drupal\block\Entity\Block;

/**
 * Implements hook_preprocess_html().
 */
function sb_test_preprocess_html(&$variables) {
//overriding the default meta view port
  $variables['page']['#attached']['html_head'][] = array(
    array(
      '#tag' => 'meta',
      '#attributes' => array(
        'name' => 'viewport',
        'content' => 'width=device-width, initial-scale=1, shrink-to-fit=no, maximum-scale=1',
      ),
    ),
    'viewport',
  );
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function sb_test_theme_suggestions_page_alter(array &$suggestions, array $variables) {

  if ($node = \Drupal::routeMatch()->getParameter('node')) {
    $content_type = $node->bundle();
    $view_mode = $node->view_mode();  ##<-- how do you get view_mode here??
    $suggestions[] = 'page__' . $content_type . '__' . $view_mode;
  }
}